### ISSUE TITLE
Change "slave-owner" to "enslaver" on Tabulator

### ISSUE THREAD

**Issue by ashleychampagne** [Brown-University-Library/disa_dj_project#105]
From email to Lin on 5/12:

Gabrielle Foreman, in her article "Writing about Slavery" recommends against using "slave-owner" language and instead using "enslaver" (see [here](https://static1.squarespace.com/static/5f48c318f66d8f4a8f4d75e1/t/5f7640b61589a316b9386945/1601585334818/%C2%A0Writing+About+Slavery+%28excerpt%29.pdf)).

Thanks, Ashley -- yes, totally agree. I think we have talked about this before but perhaps never came to a point of action? There is a small side debate in the field about whether "enslaver" applies to later purchases (vs. the person who did the original enslaver), but the bottom line is that ever person who kept a person in slavery was actively an enslaver. So I agree with the change. 

Thanks, and good luck with the presentation!
Lin

**Comment by prashleigh** [comment]
Moved to SmartSheets
