### ISSUE TITLE
Cache API json in localStorage to improve input form performance

### ISSUE THREAD

**Issue by elizabethyalkut** [Brown-University-Library/disa_dj_project#167]
```
const response = await fetch(url + id);
const json = await response.json();
localStorage.setItem('myResponse', JSON.stringify(json));
```
We'll need to set a check for when the data was last fetched/set (cf #132) and make sure it gets re-fetched at a sensible interval (12 hours?).

**Comment by prashleigh** [comment]
1. First get to page — render from cache
2. In BG, update data — re-render if change
3. Add a "Refresh data" button (with label that includes the date of the cached data)

**Comment by elizabethyalkut** [comment]
Should probably use [Cache](https://developer.mozilla.org/en-US/docs/Web/API/Cache) instead of [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage)? localStorage is key:value strings; Cache (I think) can cope with more complex objects like the browse.json response.

**Comment by elizabethyalkut** [comment]
Django [caching](https://docs.djangoproject.com/en/3.2/topics/cache/#the-low-level-cache-api) _might_ be an option but tbh I don't understand it enough.

**Comment by prashleigh** [comment]
Yes, you'd have to serialize the JSON as a string before putting it in
LocalStorage (and deserialize it on the way out). Which isn't a big deal.

Love to hear more about Cache vs LocalStorage, how they compare.

**Comment by prashleigh** [comment]
This:
https://dev.to/quokkalabs/difference-between-local-session-and-cache-storage-28bc

**Comment by prashleigh** [comment]
Here's a thought - what if, when a source is created and updated, it
updates also the cached data structure? That way it will appear in the
source list for selection, even if the cache hasn't been synced. I think
this would only be possible with LocalStorage.
