### ISSUE TITLE
Fixing Ben's virtual environment

### ISSUE THREAD

**Issue by mcakkerman** [Brown-University-Library/disa_dj_project#23]
Birkin is helping to fix Ben Tyler's virtual environment. Miscommunication between Ben's computer and virtual environment.

**Comment by mcakkerman** [comment]
Working with Birkin to try to find a solution. May have to do a fresh folder. Goal is to figure it out Friday 10/02/2020.

**Comment by bentbul** [comment]
Birkin fixed (w/ BT screen-share) on 10/5 -- updated workaround step at bottom of https://docs.google.com/document/d/1fHB_H7qm7yk3VF4UYgcZMcbcgPK64Y8D1JU8SSQ5DNU/edit?ts=5ec417c1 (for some reason, BT's macOS stopped recognizing "DISA_DJ__ENV_SETTINGS_PATH" variable if run from loaded "disa_dj_env.sh" file, but does recognize if loaded/run directly within Terminal)

**Comment by mcakkerman** [comment]
Yay! Congratulations on getting this issue fixed.
