### ISSUE TITLE
Brainstorm what user-centered form could be w/ end of Jan deadline 

### ISSUE THREAD

**Issue by ashleychampagne** [Brown-University-Library/disa_dj_project#39]

**Comment by mcakkerman** [comment]
Patrick and Birkin met to talk about weekly developments but still need to meet talk about long term minimal end of January functionality

**Comment by mcakkerman** [comment]
New agenda link
[https://docs.google.com/document/d/10HHr9JX_yiuvloqRYX2ehUsAaOP4dEwO62NZet4ICM0/edit]

**Comment by mcakkerman** [comment]
Officially closed
