### ISSUE TITLE
Add to status field

### ISSUE THREAD

**Issue by ashleychampagne** [Brown-University-Library/disa_dj_project#62]
Note on 2/18 from Zoe:

"If it's possible, it would be great to add to the dropdown list in the status box:
- Prospective Enslavement
- Formerly Enslaved"

**Comment by birkin** [comment]
A question: where should the new additions go? (By the way, it's completely ok to re-order the list in the answer.)

Desired additions...
- 'Prospective Enslavement'
- 'Formerly Enslaved'

Existing Menu...
- 'Indentured Servant'
- 'Servant'
- 'Slave'
- 'Captive'
- 'Threatened Enslavement'
- 'Indenture, Court-Ordered'
- 'Indenture, Parental'
- 'Indenture, Voluntary'
- 'Free'
- 'Unclear'
- 'Other'

**Comment by ashleychampagne** [comment]
Order identified by Lin on 2/19:

'Indentured Servant'
'Servant'
'Slave'
'Captive'
'Threatened Enslavement'
'Indenture, Court-Ordered'
'Indenture, Parental'
'Indenture, Voluntary'
'Prospective Enslavement'
'Formerly Enslaved'
'Free'
'Unclear'
'Other'

**Comment by birkin** [comment]
- implemented in commit 84354c85a19a098ec8fd05e3f969595340699dcd
