### ISSUE TITLE
Change title of project in experimental search 

### ISSUE THREAD

**Issue by ashleychampagne** [Brown-University-Library/disa_dj_project#78]
from DISA to "Stolen Relations: Recovering Stories of Indigenous Enslavement in the Americas"
This name exists both as a title and as part of the URL. 
The appropriate acronym is "SR" instead of "DISA"

**Comment by ashleychampagne** [comment]
This is the website I'm speaking to: https://cds.library.brown.edu/projects/disa/browse/

**Comment by bentbul** [comment]
updated in SM's older header by 5e0159da93bada7d28c5c26538cb8f93ec5a0127

**Comment by ashleychampagne** [comment]
Thank you, Ben. The title is still the same - does this need to be pushed to production still? Is that only something Ben can do?

**Comment by birkin** [comment]
no, @ashleychampagne , this is something i need to do, and will.

**Comment by birkin** [comment]
updated main-branch, and deployed, with @bentbul changes; closing issue.
