### ISSUE TITLE
Form labels and boxes in new form need proper alignment

### ISSUE THREAD

**Issue by ashleychampagne** [Brown-University-Library/disa_dj_project#84]
Ensure proper alignment on the form labels and boxes 
e.g. Url: https://dlibwwwcit.services.brown.edu/disa_demo/redesign_citations/975/#/1175

**Comment by bentbul** [comment]
Should be fixed/adjusted via 845c95aeb65c634943b3da39a70c7446067cb205 -- may need to be applied to additional label cases, though (whichever use tagify via <disa-tags>)
