### ISSUE TITLE
CSSJ / Acknowledgements in new_flow branch for merging

### ISSUE THREAD

**Issue by ashleychampagne** [Brown-University-Library/disa_dj_project#87]
Hi Birkin,
A note that Ben updated the acknowledgements on Tabulator (https://cds.library.brown.edu/projects/disa/browse/) to include CSSJ as one of our partners in the footer. It will be ready for your to merge and push to the server when you are ready to do so. Email below:

"Hi Ashley -- I just added CSSJ to the acknowledgements text, in the new_flow branch (via https://github.com/Brown-University-Library/disa_dj_project/commit/1e3f484794633a27839ed2bd1abbda9b653a6607), but will just need to get merged into whatever dev branch Birkin merges & pushes to the server for it to show up on the dev. server... --Ben"

**Comment by birkin** [comment]
Implemented in commit 1ee2f67abe21f0ccc59c04dc715c811f4e053f94.
