### ISSUE TITLE
Change URL to include Stolen Relations (https://cds.library.brown.edu/projects/disa/browse/) 

### ISSUE THREAD

**Issue by ashleychampagne** [Brown-University-Library/disa_dj_project#90]
URL should read: https://cds.library.brown.edu/projects/stolen-relations/browse/)

**Comment by birkin** [comment]
@ashleychampagne I've implemented this on the dev-server. I was going to wait until we moved to the new-form to make this change in production -- but I could go ahead with this if you want.

**Comment by birkin** [comment]
Implemented 2021-Sep-09-Tue.
