### ISSUE TITLE
fix how new form goes to old form

### ISSUE THREAD

**Issue by ashleychampagne** [Brown-University-Library/disa_dj_project#96]
Note from Zoe: “one thing that I noticed is that when I use the global search bar to find something in the new form, that does indeed bump me back to the old form. For example, I was on the new form citations page (the one you land on after logging in), and when I searched "wethersfield" in the search bar at the top, it brought me to this link: https://cds.library.brown.edu/projects/stolen_relations/search_results/?query=wethersfield which seems to be a part of the old form. When I click on one of the results, it definitely brings me to the old form.”

**Comment by birkin** [comment]
don't remember when, but this has been fixed, so am closing.
